name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: false
          lfs: false
          clean: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Create a temporary directory
          TEMP_DIR=$(mktemp -d)
          
          # Copy the built site to the temporary directory
          cp -R _site/* "$TEMP_DIR"
          
          # Switch to gh-pages branch (create if it doesn't exist)
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi
          
          # Clean the working directory
          git rm -rf .
          
          # Copy the built site back
          cp -R "$TEMP_DIR"/* .
          
          # Create necessary files
          touch .nojekyll
          
          # Stage and commit
          git add -A
          git commit -m "Deploy website - $(date +'%Y-%m-%d %H:%M:%S')"
          
          # Force push
          git push -f origin gh-pages
